### ISSUE TITLE
sqlite3.OperationalError in result

### ISSUE THREAD

**Issue by TangzyGabriel** [amazon-science/llm-open-domain-table-reasoner#2]
Hello, I would like to ask a question about sqlite in opentab.

I was trying to replicate the experiment result from opentab paper, I set up the environment and use bm25 for retrieval, then I perform experiment using python run_open.py and python run_closed.py. However, I found the em_acc is lower than the result in the paper. I discovered that in the output json file, most of the errors are caused by sqlite3.OperationalError, which would make the "pred_result" to be empty.

An example of such mistake looks like
"error": "(sqlite3.OperationalError) near \"SQLite\": syntax error\n[SQL: SQLite:\nSELECT name, career_nwin_loss FROM Fabrice_Santoro;]\n(Background on this error at: https://sqlalche.me/e/14/e3q8)",

I would like to ask if you know the cause of such errors, could it be the case that I did not set up the sqlite db appropriately or there are other possible causes?

**Comment by Vencin-Z** [comment]
I also meet this problem.Have  you sloved  it now?

**Comment by TangzyGabriel** [comment]
@Vencin-Z Unfortunately I haven't solve it yet. I am not sure if the problem is caused by different version of GPT used in experiment. I used third party API to access GPT-3.5-turbo but in the experiment of opentab paper it seems the GPT-3.5-turbo-0613 (which is deprecated now) is used instead.

**Comment by rudra0713** [comment]
I am running into an even more basic problem. When I run run_open.py file, I am getting the error:
`
Traceback (most recent call last):
  File "/scratch/rrs99/llm-open-domain-table-reasoner/scripts/program_main.py", line 13, in <module>
    from generation.generator import Generator
  File "/scratch/rrs99/llm-open-domain-table-reasoner/scripts/../generation/generator.py", line 10, in <module>
    from text_generation import Client
ModuleNotFoundError: No module named 'text_generation'
`
I checked the generation directory, there is no file named text_generation. Am I missing something obvious?
